.github/workflows/ci.yml
app/composer.json
app/composer.lock

This PR updates the PHP version used in CI to 8 (matching the Docker dev environment) and uploads html test coverage reports as build artefacts.

Upload test coverage reports as build artifacts

---

app/app/Actions/ScrapeDocumentInfoAction.php
app/app/Actions/ScrapeMemberGroupsAction.php
app/app/Actions/ScrapeMemberInfoAction.php
app/app/Actions/ScrapeMembersAction.php
app/app/Actions/ScrapeProcedureAction.php
app/app/Actions/ScrapeVoteResultsAction.php
app/app/Providers/AppServiceProvider.php
app/routes/console.php
app/tests/Unit/Actions/ScrapeDocumentInfoActionTest.php
app/tests/Unit/Actions/ScrapeMemberGroupsActionTest.php
app/tests/Unit/Actions/ScrapeMemberInfoActionTest.php
app/tests/Unit/Actions/ScrapeMembersActionTest.php
app/tests/Unit/Actions/ScrapeProcedureActionTest.php
app/tests/Unit/Actions/ScrapeVoteResultsActionTest.php

Remove redundant “and save” from action names

Rename scraper actions

---

.github/dependabot.yml

Right now, Dependabot checks for updates of PHP and Python packages every day. That’s a little annoying and tbh it’s not really important that we’re always on the latest minor version of every package. I updated the Dependabot settings to check for updates on a weekly basis from now on. (We’ll still be notified of critical updates/security patches out of schedule.)

Weekly Dependabot updates

---

app/app/Console/Kernel.php

The `scrape:members-info` command doesn’t accept a `--term` option (because the scraped information doesn’t depend on the parliamentary term).
Close #199

Fix cronjob error

---

ansible/roles/setup/tasks/main.yml

As described [here](https://github.com/WICG/floc#opting-out-of-computation) website administrators can opt-out of Google’s new Federated Learning of Cohorts using a Permissions-Policy header. Sites that set the header won’t be included in the cohort calculation.
Closes #241

Set Google FLoC opt out header

---

app/app/Mixins/AbstractRenderedMixin.php
app/app/Mixins/TestResponseMixin.php
app/app/Mixins/TestViewMixin.php
app/app/Providers/AppServiceProvider.php
app/composer.json
app/composer.lock
app/tests/Feature/Http/Monitoring/IndexTest.php
app/tests/Feature/Http/VotingLists/ShowTest.php
app/tests/Pest.php
app/tests/Unit/Components/ThumbTest.php
app/tests/Unit/Components/VoteResultChartBarTest.php
app/tests/Unit/Components/VoteResultChartTest.php

This adds two PHPUnit assertion methods and the respective Pest expectations to the two relevant classes `TestView` and `TestResponse`. An instance of `TestView` ist returned e.g. when we render an isolated Blade component, e.g. like this:
```php
$view = $this->blade('<x-thumb result="adopted" />');
```
An instance of `TestResponse` is returned when we send a response in our HTTP feature test, e.g. like this:
```php
$response = $this->get('/votes/1');
```
In both cases, it would be handy to be able to assert that a particular elements exists using CSS selectors, e.g. like this:
```php
$response->assertSelector(‘.thumb—adopted.thumb--circle’);
```
Right now, we work around this using `assertSee`, e.g. like this
```php
$response->assertSee(‘thumb--adopted thumb--circle’)
```
This works, but …

Selector assertions

---

ansible/roles/deployment/tasks/main.yml
app/.gitignore
app/app/Http/Kernel.php
app/composer.json
app/composer.lock
app/config/app.php
app/public/.htaccess

All our contents are 100% static & public, i.e. there’s no need to regenerate them on every request.
The `page-cache` package caches the response of GET requests in static HTML files on the file system. On subsequent requests, the webserver can directly serve these static pages, i.e. the webserver doesn't even need to pass on the request to PHP. For example, after requesting `/votes/1`, the following static directory structure will be created:
```
$ tree page-cache/
page-cache/
|-- pc__index__pc.html
`-- votes
|-- 1.html
```
I’ve added a step to our Ansible deployment role to clear the cache on every deployment. We might also want to clear the cache for individual votes etc. whenever we re-scrape data for them.

Add static page cache

---

app/Dockerfile
app/app/Actions/CreateMemberThumbnailAction.php
app/app/Http/Controllers/VotingListsController.php
app/app/Member.php
app/composer.json
app/composer.lock
app/config/app.php
app/config/image.php
app/public/.htaccess
app/resources/views/components/member-list-item.blade.php
app/routes/console.php

Currently, we embed photos of MEPs directly from the Parliament’s website. This is unfortunate for two reasons:
1. Hotlinking is usually unwanted by the host of the media as it increases traffic cost etc.
2. The browser has to open a connection to a separate host, increasing loading times. More importantly, the original images are way larger than what we actually display. If we create thumbnails in the correct size, we can reduce file sizes for the individual member photos from ~50kB to 2-3kB.

Create avatar thumbnails

---

app/composer.json

This was intended as a workaround for the problem that we need to run artisan config:cache after running tests in order to access the local database afterwards. However, this is not a suitable workaround since there is no option to provide arguments to a specific command in a script list as used here. This leads to the name of the test file to execute when running only one test file to the cache:clear command that errors.

Remove config:cache from composer test script

---

scrapers/ep_votes/scrapers.py
scrapers/tests/test_scrapers.py

In the vote collection tables on the parliaments website, sometimes the indicator for lapsed votes is put in an unexpected column (i.e. remarks instead of votes). This lead to us not excluding the row and thus votes without a result.

Fix a bug where lapsed votes where not excluded when scraping

---

app/app/Actions/MatchVotesAndVotingListsAction.php
app/tests/Unit/Actions/MatchVotesAndVotingListsActionTest.php

When matching votes with voting lists, we want to report any issues silently, i.e. matching should not fail/be aborted.

Don't fail on exceptions during vote matching

---

.github/workflows/ci.yml
app/phpunit.xml

Setting the env variable in `phpunit.yml` will make sure we always use the collection driver when running tests, no matter wether they are executed locally or in CI.

Use collcetion driver when running tests

---

app/app/Session.php
app/resources/views/voting-lists/index.blade.php
app/tests/Feature/Http/VotingLists/IndexTest.php

@tillprochaska neuer Versuch upside_down_face
Ich bin mir nicht sicher, ob wir die neue Funktion brauchen oder haben wollen.
Es hat aber am Ende überwogen, dass ich dachte vielleicht will man (aus welchen Gründen auch immer) mal einfach alle primary votes haben, egal ob sie zugeordnet wurden oder nicht. Daher die neue Methode.
P.S. Sorry für den doppelten Spam.

Exclude non-matched primary votes from /votes index page

---

ansible/vars/general.yml

We ran into a bug because isocalendar in Python 3.8 returns a tuple, but we were expecting a named tuple.

Upgrade to Python 3.9

---

app/resources/js/components/search.js

The template uses the session id as a key in for loops, however, it has previously been undefined, confusing Alpine.js when trying to render the results.

Add session id

---

app/resources/js/components/search-results-page.js

Instead, simply replace the current URL, keeping the browser’s back button usable.
Close #492

Do not push updated search query to history

---

app/app/Console/Kernel.php
app/routes/console.php

Our current logic to automatically import new vote results doesn't work out… 🙃 Each Sunday, we’re trying to import vote results for the current week (i.e. the previous seven days). However, all documents are usually only available in the week following the plenary session.
This commit changes the `scrape:all` command.
It doesn't accept `from` and `to` options anymore. Instead, it tries to find the oldest session that has no associated votes and uses that session’s start and end date to scrape votes and voting lists.
That way, no matter when both votes and voting lists become available, we’ll import them. There’s one problematic case: If there’s a session without votes (be that a valid session or a session that for some reason didn’t actually take place), we’d try to scrape votes for that …

Fix automated scraper runs

---

app/app/Http/Controllers/VotingListsController.php
app/resources/lang/en/voting-lists.php
app/resources/views/components/voting-list/download-panel.blade.php
app/routes/web.php
app/tests/Feature/Http/VotingLists/JsonTest.php

Implements issue [568](https://github.com/HowTheyVote/epvotes/issues/568). 
This PR adds a new endpoint which is returning the voting results as a JSON. Moreover it adds a new button in the frontend to download the json:

Add JSON endpoint for vote results

---

.github/workflows/ci.yml
ansible/roles/deployment/tasks/main.yml
app/composer.json

Composer recently introduced a change that will prompt you to confirm to install any plugins that come with packages. This is the case for pest, so our CI runs failed after reaching a timeout, because composer waited for user input.
The solution is to add the pest plugin to our `composer.json`, and in general (and to prevent similar issues in the future) to run composer commands non-interactively in CI/CD.

Fix `composer install` in CI/CD

---

.github/workflows/ci.yml
ansible/roles/deployment/templates/etc/services.d/epvotes-scrapers.ini.j2
ansible/vars/general.yml
app/resources/lang/en/components.php
app/routes/console.php
docker-compose.yml
scrapers/Dockerfile
scrapers/poetry.lock
scrapers/pyproject.toml

The change in the `Dockerfile` resolves the problem that I mentioned where `poetry` will insist on using outdated envs on systems where the container existed previously. On a "fresh" clone/machine the dependency issues we talked about where non-existent.
I already tried starting the `gunicorn` server instead of the `flask` one locally and made sure that I can run scrapers.
I propose that I deploy this branch once after you gave :heavy_check_mark: and before merging, to make sure that everything works remote as expected.
By the way, if you test this locally, rebuilding the container, even without any caches, was not enough for me, I had to also go into the container and run another `poetry install`.

Update to python3.10 and resolve dependency problems / Stop using werkzeug for prod

---

scrapers/ep_votes/scrapers.py
scrapers/tests/test_scrapers.py

The 0 went missing due to typeconversions, i.e. even if we supplied the initial values with leading 0, when converting them to ints, they went amiss.
Fixes https://sentry.io/share/issue/a93a8620ca21413d9d5b5f7027b3a399/.

Fixup missing 0 to construct isoformat date string

---

ansible/roles/setup/tasks/main.yml
ansible/vars/general.yml

This fixes a compatibility problem between poetry `1.2.0` and `1.1` which caused `setuptools` to go amiss, resulting in the scraper service being unable to start.
Closes #754. I deployed this branch and made sure that the scrapers are indeed running.

Enforce (current) `poetry` version

---

app/database/migrations/2022_09_20_134047_add_ignore_when_scraping_voting_lists_column_on_sessions_table.php
app/routes/console.php

This fixes a crash that occurs when we try to scrape the voting lists for a Session that has no voting lists in scrape:all. In the future, we can manually mark such Sessions. I opted for manual marking as the implications of exempting a Session are quite severe and this case is very rare.

Add switch to manually exempt Sessions from voting list scraping

---

app/routes/console.php
scrapers/ep_votes/scrapers.py

The usage of the alternate name is what broke our neck yesterday.
What I believe happened is, that the EP profile for her in the past gave the name "Miranda Paz", as can be seen with the [wayback machine](http://web.archive.org/web/20191230024743/http://www.europarl.europa.eu/meps/en/24942/ANA+MARIA_MIRANDA+PAZ/history/8). When she came into parliament again this year (during the "summer pause"), this changed to just Miranda. We scraped that change and adapted our entry in the members database accordingly.
In the past, we introduced the alternate name, as we matched based on "Miranda Paz", while the Voting Lists from the Parliament **always** just contained Miranda.
As this is now consistent within the original data sources from the parliament, the alternate name broke the scraping, as …

Fixes for current deployment

---

.github/workflows/ci.yml
ansible/vars/general.yml
app/.gitignore
app/.php-cs-fixer.php
app/Dockerfile
app/app/Actions/ScrapeSessionsAction.php
app/app/Actions/ScrapeVoteCollectionsAction.php
app/app/Http/Controllers/MembersController.php
app/app/Http/Controllers/VotingListsController.php
app/app/Mixins/CollectionMixin.php
app/app/Mixins/ComponentAttributeBagMixin.php
app/app/Mixins/StrMixin.php
app/app/VotingList.php
app/composer.json
app/composer.lock
app/resources/js/components/search-results-page.js
app/resources/views/components/search-results-page.blade.php
app/resources/views/components/search-results-page/result.blade.php
app/resources/views/members/show.blade.php
app/tests/Feature/Http/Members/ShowTest.php
app/tests/Feature/Http/VotingLists/JsonTest.php
app/tests/Feature/Http/VotingLists/ShowTest.php
docker-compose.yml

Newer versions of Meilisearch support nested objects. This allows us to reuse our existing search UI (which fetches votes directly from the search index). This has two advantages:
1) The votes displayed on member profiles are often out of date, because we cache them statically. When dynamically rendering votes, the most recent votes will always be “fresh”, as they are fetched from the search index.
2) We can search for a certain keyword or topic and see at a glance how an MEP voted in multiple votes matching the search term.
With nested index objects, we can index a vote like this (where 1234 and 5678 are the IDs of members):
```
{
"title": "Lorem Ipsum",
"result": "ADOPTED",
…
"members": {
"1234": "FOR",
"5678": "AGAINST",
…
}
}
```
We can then retrieve only the voting for a single …

Members votes search

---

ansible/roles/meilisearch/tasks/installation.yml

Compiling the most recent release failed, but they now provide prebuilt binaries, so I updated the Ansible roles to use that instead of building from source.

Fix meilisearch role

---

app/routes/console.php

Correctly log output of subcommands when running `scrape:all`

---

scrapers/ep_votes/scrapers.py

These additions are necessary in order to successfully scrape the January Session of 2023.
Please be aware that I made them on the server as well, in order to collect the data, so we need to reset that for the deployment to succeed.

Add two alternative names from January sessions

---

app/routes/console.php

Previously, the VOT XML files (corresponding to the tables of votes) contained the same contents for each day in a session where votes were held.
This was changed recently, so that e.g., these files for [15.03](https://www.europarl.europa.eu/doceo/document/PV-9-2023-03-15-VOT_EN.xml) and for [16.03](https://www.europarl.europa.eu/doceo/document/PV-9-2023-03-16-VOT_EN.xml) are different.
This change was done in a way that affects (as far as I can tell) all older files as well.
This was the cause of us only retrieving vote collections for a single day of sessions over the last months.

Adapt scraping logic to fit separate vote collection files for each day

---

scrapers/ep_votes/scrapers.py
scrapers/tests/test_scrapers.py

We previously assumed, that a session never spans multiple years or months. This assumption does not hold, and the first such session that we  encountered lead to a faulty session entry that in turn got displayed on the landing-page in a nonsensical way. This removes the assumption of a session never spanning multiple months. For years, we still keep our assumption.
Closes #882.

FIx `ParliamentSessionsScraper` for Sessions that span multiple months

---

.github/dependabot.yml

This makes it easier to review and update dependencies and prevents the history getting cluttered with Dependabot commits.

Group minor/patch dependency updates

---

backend/howtheyvote/alembic/versions/9b35d19b64c4_add_term_column_to_votes_table.py
backend/howtheyvote/cli/temp.py
backend/howtheyvote/models/vote.py
backend/howtheyvote/scrapers/votes.py
backend/howtheyvote/store/mappings.py
backend/tests/scrapers/test_votes.py

We know the term for every vote we scrape, but we currently do not store it in the `votes` table.
Being able to filter votes by term is useful, for example in order to create exports separately for every term (so they don’t become huge), to search within votes of the current term, …
While it’s possible to derive the term from the date, simply storing it as a separate column is much easier :)

Add term column for votes

---

backend/howtheyvote/helpers.py
backend/tests/test_helpers.py

Some Markdown renderers convert even a single line break to a <br> which is undesired in this case.

Remove single line breaks in documentation

---

backend/howtheyvote/export/__init__.py

We use the Readme in release notes on howtheyvote/data, and releases already have a headline. The intro text is also kinda redundant.

Remove heading from export Readme

---

frontend/src/components/CountriesFilterSelect.tsx
frontend/src/components/GroupsFilterSelect.tsx

When I filtered a bunch in order to prepare some slides for our talk, I found that not having the lists sorted by alphabet is a bit stressful. This makes it way easier in my opinion to find the country one is looking for. I have basically sorted the group list for the sake of consistency. The sorting in the position dropdown makes sense as is in my opinion, and also we know for sure that these options will never change, which is (more or less in theory) possible for the other values.

Sort groups and countries alphabetically instead of implicitly by size

---

frontend/src/components/Disclosure.css
frontend/src/components/FilterSelect.css
frontend/src/components/VoteCard.css
frontend/src/css/base.css
frontend/src/css/variables.css

This solves a number of issues related to focus outlines, specifically:
* Increase contrast on dark backgrounds (such as on the home page). Ideally, we’d have a two-color outline (one dark color and one light color), but I think there’s still no straight-forward way to achieve that with the `outline` property.
* Fixes an issues where the outline wasn’t fully visible in search results.

Fix focus outline

---

backend/howtheyvote/scrapers/votes.py
backend/tests/scrapers/data/votes/procedure_ficheprocedure-2023-2019-ini.html

The markup of the OEIL has changed and the previous selector to extract the procedure title didn’t work any more. Also updated the tests fixture with the current version of the web page.

Update scraper after markup of source website changed

---

backend/howtheyvote/api/votes_api.py
backend/howtheyvote/store/index.py
backend/tests/api/test_votes_api.py

In some cases, we cannot extract any title (vote title or procedure title) for a given vote. In that case, we cannot display anything about this vote in the frontend, so we should probably just hide it.
After deployment run the following commands:
```
htv system delete-indexes
htv system upgrade
htv aggregate votes
```

Do not display votes with empty titles

---

backend/howtheyvote/analysis/votes.py
backend/howtheyvote/pipelines/rcv_list.py
backend/tests/analysis/test_votes.py
backend/tests/helpers.py
backend/tests/scrapers/helpers.py
backend/tests/scrapers/test_votes.py

Until now, we’ve decided whether a vote is a main vote solely based on the description of a vote. However, in rare cases a main vote may not have description and only a title (e.g. in case of the election of the Commission). I’ve updated the analyzer to handle votes based on title in addition to the existing heuristic.

Update main vote analyzer to also handle special vote titles 

---

frontend/src/pages/HomePage.css
frontend/src/pages/HomePage.tsx

This fixes a small visual issue: In some cases, line breaks were inserted in formatted dates (for example `Nov[break]28`). This PR fixes that by using non-breaking spaces in formatted dates and also improves the visual appearance by ensuring that the lines are roughly the same length (using `text-wrap: balance`).
**Before:**
**After:**

Prevent line breaks within formatted date

---

.github/workflows/backend.yml
backend/Dockerfile

A new major version of Poetry has been released which includes some breaking changes related to project configuration: https://python-poetry.org/blog/announcing-poetry-2.0.0
For now, this pins to Poetry < 2.0

Temporarily pin Poetry to <2.0

---

backend/howtheyvote/alembic/versions/1f516b18c4f6_rename_result_column_to_status.py
backend/howtheyvote/alembic/versions/2f958a6f147d_add_checksum_column_to_pipeline_runs_.py
backend/howtheyvote/models/__init__.py
backend/howtheyvote/models/common.py
backend/howtheyvote/pipelines/__init__.py
backend/howtheyvote/pipelines/common.py
backend/howtheyvote/pipelines/members.py
backend/howtheyvote/pipelines/press.py
backend/howtheyvote/pipelines/rcv_list.py
backend/howtheyvote/pipelines/sessions.py
backend/howtheyvote/scrapers/common.py
backend/howtheyvote/worker/__init__.py
backend/howtheyvote/worker/worker.py
backend/tests/helpers.py
backend/tests/pipelines/data/rcv-list_pv-9-2024-04-24-rcv-fr-evening.xml
backend/tests/pipelines/data/rcv-list_pv-9-2024-04-24-rcv-fr-noon.xml
backend/tests/pipelines/test_rcv_list.py
backend/tests/scrapers/helpers.py
backend/tests/scrapers/test_members.py
backend/tests/scrapers/test_sessions.py
backend/tests/scrapers/test_votes.py
backend/tests/worker/test_worker.py

While on most plenary days, there is only one voting session around midday, on some days there is another sesssion in the evening, usually around 17:00. The vote results of the evening sessions are appended to the same source document that also contains the results of the midday votes.
Currently, we only run the `RCVListPipeline` between 12:00 and 15:00 until we’ve been able to fetch vote results successfully. Once we’ve fetched the results, we do not attempt to fetch them again. That means that so far we did not (automatically) fetch results of the evening voting session.
The easy approach to this problem would be to simply keep running the `RCVListPipeline` until the evening, even after it has successfully completed for the first time. However, this approach has a few disadvantages:
* …

Fetch results of evening voting sessions

---

frontend/src/pages/HomePage.tsx

I think with the recent `openapi-ts` upgrade the naming convention for parameter names changed. As a result, the parameters are ignored and currently an incorrect date is displayed on the homepage. Also checked that there are no other similar issues like this.

Fix last session on homepage

---

backend/howtheyvote/pipelines/common.py
backend/howtheyvote/pipelines/rcv_list.py
backend/howtheyvote/worker/__init__.py
backend/howtheyvote/worker/worker.py

These are not errors, so they should have no suffix at all. See: https://peps.python.org/pep-0008/#exception-names
Fixes #1077

Rename exceptions to follow PEP8

---

backend/howtheyvote/cli/dev.py
backend/howtheyvote/data.py
backend/howtheyvote/data/countries.json
backend/howtheyvote/data/eurovoc.json
backend/howtheyvote/data/groups.json
backend/howtheyvote/models/eurovoc.py
backend/tests/test_data.py

This fixes the last remaining task in #960.
I’ve also implemented a few small changes to sort records and list values. This should make it much easier to diff the resulting JSON files. (Right now, rerunning some of the `htv load-*` commands can lead to large diffs, even though there have been only small or no changes.)
Also had to fix how we send SPARQL requests because some SPARQL endpoints now only accept POST requests. (We were using GET requests before.)

Update groups, countries, Eurovoc terms

---

frontend/src/components/Tag.css
frontend/src/components/Tag.tsx
frontend/src/components/VoteCard.tsx
frontend/src/pages/AboutPage.tsx

We still use this under the hood, especially to inform the ranking. However, as we got quite a bit of feedback that it is not clear what this actually means, we remove it from the frontend for now.
We briefly discussed whether to rename it to something more telling, but decided against it, as our goal should be to get press releases/additional information for as many votes as possible anyways.

Remove "Featured" indicator in frontend

---

backend/howtheyvote/scrapers/press_releases.py
backend/tests/scrapers/data/press_releases/press-release_20221014IPR43206.html
backend/tests/scrapers/data/press_releases/press-release_20241212IPR25960.html
backend/tests/scrapers/test_press_releases.py

The OEIL URLs have changed from `https://oeil.secure.europarl.europa.eu/oeil/popups/ficheprocedure.do?lang=en&procedure=...` to `https://oeil.secure.europarl.europa.eu/oeil/en/procedure-file?reference=...`. Old press releases still use the old-style links, so we have to support both.

Fix press releases procedure extraction

---

backend/howtheyvote/alembic/versions/3895af031aea_add_responsible_committee_column_to_.py
backend/howtheyvote/api/openapi_spec.py
backend/howtheyvote/api/serializers.py
backend/howtheyvote/api/votes_api.py
backend/howtheyvote/cli/dev.py
backend/howtheyvote/data.py
backend/howtheyvote/data/committees.json
backend/howtheyvote/export/__init__.py
backend/howtheyvote/models/__init__.py
backend/howtheyvote/models/committee.py
backend/howtheyvote/models/vote.py
backend/howtheyvote/scrapers/votes.py
backend/howtheyvote/store/mappings.py
backend/pyproject.toml
backend/tests/api/test_votes_api.py
backend/tests/export/test_init.py
backend/tests/scrapers/test_votes.py

This PR includes changes to scrape the committee responsible for the legislative procedure a vote belongs to. We already scrape information about the procedure from the OEIL, so I simply extended what information the existing scraper extracts.
Similar to countries and political groups, I’ve loaded a list of all committees using the SPARQL endpoint of the Publications Office.
I’ve added the responsible committee to API responses and the CSV export, but for now it’s not displayed in the UI or available as a filter etc.

Scrape procedure committee

---

backend/Dockerfile
frontend/Dockerfile

Follow up to 9f243166c95f80c3252b231cd9e0a37baefe968a. I’ve also sneaked in a small change to reduce the number of Docker layers for the backend and frontend images.

Fix installing Python dependencies in Dockerfile

---

frontend/src/pages/SearchPage.tsx

Currently, when going on the search page, specifying a non-default sorting order and afterwards clicking the arrow to navigate to the second page, the sorting option will not be respected, effectively making it impossible to paginate through results not ordered by relevance.
This PR fixes that.

Respect specified sort option when paginating through results

---

backend/howtheyvote/alembic/versions/2fb74cc3d20c_add_text_and_position_counts_column_to_press_releases_table.py
backend/howtheyvote/alembic/versions/848ef24718dd_add_press_release_column_to_votes_table.py
backend/howtheyvote/analysis/__init__.py
backend/howtheyvote/analysis/helpers.py
backend/howtheyvote/analysis/press_releases.py
backend/howtheyvote/analysis/votes.py
backend/howtheyvote/api/votes_api.py
backend/howtheyvote/cli/temp.py
backend/howtheyvote/models/__init__.py
backend/howtheyvote/models/press_release.py
backend/howtheyvote/models/vote.py
backend/howtheyvote/pipelines/press.py
backend/howtheyvote/query.py
backend/howtheyvote/scrapers/press_releases.py
backend/howtheyvote/store/index.py
backend/howtheyvote/store/mappings.py
backend/howtheyvote/vote_stats.py
backend/tests/analysis/test_helpers.py
backend/tests/analysis/test_press_releases.py
backend/tests/analysis/test_votes.py
backend/tests/scrapers/data/press_releases/press-release_20190712IPR56948.html
backend/tests/scrapers/data/press_releases/press-release_20250204IPR26689.html
backend/tests/scrapers/test_press_releases.py
backend/tests/test_query.py
backend/tests/test_vote_stats.py

We can currently only match press releases with votes if the press release references a report or procedure. For non-legislative procedures, this is usually not the case. However, even press releases about non-legislative procedures usually mention the vote results (how many MEPs voted for/against/abstained). If there is exactly one vote with the same result on the day of the press release, we can use that info to match the press release to the vote.
I’ve implemented this as follows:
* As a first step, we now scrape the full text of a press release and try to extract vote results ("the text was adopted with x votes in favour, y against, and z abstentions" and similar wordings).
* Previously, we matched press releases to votes "on the fly" based on document and procedure references (which …

Match press releases and votes based on vote result

---

backend/howtheyvote/metrics.py
backend/howtheyvote/pipelines/rcv_list.py
backend/howtheyvote/worker/worker.py

* `htv_worker_pipeline_last_run_timestamp_seconds`: Useful to set up alerts if a pipeline hasn’t run for some time
* `htv_sharepics_generated_total`: Useful to set up alerts if a lot of sharepics fail to generate
* `htv_next_session_seconds`: Useful to set up notifications when a new plenary session has started

Add new Prometheus metrics

---

backend/howtheyvote/__init__.py
backend/howtheyvote/wsgi.py

We use structlog for logging and set it up to emit JSON formatted logs. Flask also emits some logs by default, e.g. in case of an unhandled exception. These were logged using a standard library logger so far (i.e. not as JSON).
I’ve now configured Flask to use a structlog logger. In addition, matched endpoint, request path and query string are added to all logs to ease debugging. Here’s what the logs look like in case of an unhandled exception:
```json
{
"event": "Exception on /api/votes/search [GET]",
"endpoint": "api.votes_api.search",
"path": "/api/votes/search",
"query_string": "q=lorem%20ipsum",
"logger": "howtheyvote.wsgi",
"level": "error",
"timestamp": "2025-03-14T21:40:52.732049Z",
"exception": "Traceback (most recent..."
}
```
To test this, Flask has to run in production mode. …

Configure Flask app logger

---

backend/howtheyvote/alembic/versions/7c9e86276c6d_remove_is_featured_column_from_votes_.py
backend/howtheyvote/api/query.py
backend/howtheyvote/api/serializers.py
backend/howtheyvote/export/__init__.py
backend/howtheyvote/metrics.py
backend/howtheyvote/models/vote.py
backend/howtheyvote/search.py
backend/howtheyvote/store/index.py
backend/howtheyvote/store/mappings.py
backend/tests/api/test_query.py
backend/tests/api/test_votes_api.py
backend/tests/export/test_init.py
frontend/src/api/generated/types.gen.ts

This PR includes three changes to the CSV export:
**Remove `is_featured` column**
Discussed before, closes #1117. This removes the column everywhere (including from the API and exports). Whether a vote has a corresponding press release is still a ranking factor, but it’s now named `has_press_release` in the search index which should be more obvious (but isn’t exposed publicly).
**Include EuroVoc concepts**
While exposed via the API, we haven’t included the EuroVoc concepts in the export so far. This adds `eurovoc_concepts.csv` and `eurovoc_concept_votes.csv` to the export.
**Include geographic areas**
We already have `countries.csv` which includes data about the EU member states and is referenced by the MEPs export. This adds a separate table `geo_areas.csv` for the geographic areas …

Add EuroVoc concepts, geographic areas to CSV export

---

backend/howtheyvote/api/serializers.py
backend/howtheyvote/api/votes_api.py
backend/howtheyvote/export/__init__.py
backend/howtheyvote/helpers.py
backend/howtheyvote/models/__init__.py
backend/howtheyvote/models/vote.py
backend/howtheyvote/scrapers/votes.py
backend/tests/api/test_votes_api.py
backend/tests/export/test_init.py
backend/tests/test_helpers.py

This adds the procedure type as a separate field to the API and CSV export. As the procedure type is a part of the procedure reference (e.g. "COD" in "1234/2025(COD)"), technically, this is already part of API responses and CSV exports. However, in practice, it’s quite convenient to have this exposed as a separate field for filtering etc.

Add procedure type to API and export

---

backend/howtheyvote/api/query.py
backend/stubs/xapian/__init__.pyi
backend/tests/api/test_votes_api.py

The idea behind this was to boost results that contain the search query in the same order. However, this was causing errors for nested search queries (and queries that were parsed as such), because Xapian supports phrase queries only if all subqueries are leaf queries.
Not sure if there is a good alternative. For now, I’m simply removing this. I’ve also removed the option to use `+` and `-` operators, as these are also commonly used as normal characters in search queries (e.g. date ranges).
One example to reproduce this is the query from the test case: `Union Secure Connectivity Programme 2023-2027`

Remove phrase subquery

---

backend/howtheyvote/alembic/versions/8d1995cb0bed_make_responsible_committee_column_json_.py
backend/howtheyvote/api/serializers.py
backend/howtheyvote/export/__init__.py
backend/howtheyvote/models/vote.py
backend/howtheyvote/scrapers/votes.py
backend/howtheyvote/store/mappings.py
backend/tests/api/test_votes_api.py
backend/tests/export/test_init.py
backend/tests/scrapers/data/votes/oeil-procedure-file_2024-0258-cod.html
backend/tests/scrapers/test_votes.py

A procedure can have multiple responsible committees (see [Rules of Procedure](https://www.europarl.europa.eu/doceo/document/RULES-9-2022-07-11-RULE-058_EN.html) and an [example procedure](https://oeil.secure.europarl.europa.eu/oeil/en/procedure-file?reference=2024/0258(COD))).
* I’ve updated the procedure scraper to properly handle procedures with a joint committee responsible and added tests.
* I’ve updated the CSV export and removed the `responsible_committee_code` in the `votes.csv` table. Instead, there are now separate tables `committees.csv` and `responsible_committee_votes.csv`.
After deployment, we need to re-scrape the procedure files and then re-aggregate the votes.
Fixes #1121

Handle votes with joint responsible committees

---

backend/howtheyvote/scrapers/votes.py

Similar to the RCV data source, the web server doesn’t return the correct charset in the response headers, so we need to specify it explicitly.

Enforce response encoding for VOT lists

---

.env.template
backend/howtheyvote/config.py
backend/howtheyvote/pipelines/rcv_list.py
backend/howtheyvote/pushover.py
backend/howtheyvote/worker/__init__.py
backend/howtheyvote/worker/worker.py
backend/poetry.lock
backend/pyproject.toml
backend/tests/conftest.py
backend/tests/test_pushover.py
backend/tests/worker/test_worker.py
docker-compose.yml

This uses Pushover to send notifications for important events:
* New vote results are available.
* A pipeline fails. (If data isn't available yet, that isn't considered a pipeline failure and no notification is sent.)
* Generating sharepics fails. (This sends only one notification per pipeline run, even if multiple sharepics couldn’t be generated.)
In the future, I’d like to also implement notifications when we attempt to scrape a pipeline data source for the last time and data still isn’t available.
To test this:
1. Sign up for a [Pushover](https://pushover.net/) account
2. Create a new [API application](https://support.pushover.net/i175-how-to-get-a-pushover-api-or-pushover-application-token)
3. Add the API token and your user key (from the Pushover dashboard) to your `.env` file
4. …

Send Pushover notifications for important events

---

docker-compose.yml

This was a ride :)
The share-picture generation itself works nicely, hence the pictures are generated when on executes `htv pipeline rcv-list` in production or locally **inside of the backend container**.
However, the scheduled runs are, to my understanding, not actually run inside of that container, but in the **worker**. 
The worker container however did not have access to the chromium container for making the screenshots and also was missing the local URL to display the page to be screenshot.
To confirm that I was not entirely on the wrong track, I first executed the pipeline locally in the worker container, confirmed it failed, made the changes, and afterwards re-executed the pipeline in the worker container locally again to confirm that the screenshots were in the expected location …

Fix generation of share-pictures in worker (for scheduled runs)

---

backend/howtheyvote/alembic/versions/184528e5ba14_add_idempotency_key_to_pipeline_runs_.py
backend/howtheyvote/models/common.py
backend/howtheyvote/worker/__init__.py
backend/howtheyvote/worker/worker.py
backend/tests/pipelines/data/document_a-9-2024-0163-en.html
backend/tests/pipelines/data/oeil_2024-2006-reg.html
backend/tests/pipelines/test_rcv_list.py
backend/tests/worker/test_init.py
backend/tests/worker/test_worker.py

VOT lists currently have to be run manually. In contrast to RCV lists, VOT lists are usually published with at least one day of delay. That means we have to retry fetching VOT lists for multiple days until the data becomes available.
To solve this, I’ve added "idempotency keys" to scheduled pipelines. If such a key is given, a pipeline will only be executed until it has been executed successfully for the first time.
As the existing scheduling logic for RCV pipelines was mostly untested, I’ve added test coverage and then refactored it to also make use of idempotency keys.
Finally, I’ve added the actual scheduling of VOT lists.
Most of the diff is due to new tests, the number of lines added for the idempotency keys is fairly small. It works quite well for the RCV use case, but I think the …

Add scheduling for VOT pipelines

---

backend/tests/scrapers/test_votes.py

This test ensures that the `VOTListScraper` doesn’t use a French version of the VOT list when the English translation isn’t yet available. There’s no way to test this against live data (except in the short time frame between a session and the time when the translations are published).

Don’t run test against live data (to fix scheduled scraper tests)

---

backend/howtheyvote/cli/__init__.py
backend/howtheyvote/cli/flush.py

Pipelines/scrapers only insert or update fragments, but they never delete them. That means if a fragment has been written erroneously (either because of an error in the source data or because of a bug in the software) it has to be deleted explicitly.
This adds a CLI command to manually delete fragments. Usage examples:
```
htv flush votes --id 12345
htv flush votes --id 12345 --id 67890
htv flush votes --date 2025-09-20
htv flush votes --source-name RCVListScraper
htv flush votes --source-name RCVListScraper --id 12345
```
Fixes #1171

Add CLI command to delete fragments
