.vscode/snippets.code-snippets
app/app/Actions/ScrapeAndSaveDocumentInfoAction.php
app/app/Actions/ScrapeAndSaveProcedureAction.php
app/app/Document.php
app/app/Enums/ProcedureTypeEnum.php
app/app/Procedure.php
app/database/factories/ProcedureFactory.php
app/database/migrations/2021_02_07_094738_create_procedures_table.php
app/database/migrations/2021_02_07_102027_add_procedure_id_column_to_documents_table.php
app/tests/Unit/Actions/ScrapeAndSaveDocumentInfoActionTest.php
app/tests/Unit/Actions/ScrapeAndSaveProcedureActionTest.php
app/tests/Unit/Actions/ScrapeAndSaveVoteResultsActionTest.php
app/tests/data/procedure.json
scrapers/ep_votes/api.py
scrapers/ep_votes/models.py
scrapers/ep_votes/scrapers.py
scrapers/tests/data/procedure-b9-0154-2019.xml
scrapers/tests/test_models.py
scrapers/tests/test_scrapers.py

Add procedure scraper

---

app/database/factories/TermFactory.php

Use highest used number + 1 in TermFactory instead of random number

---

app/app/Actions/ScrapeVoteResultsAction.php
app/database/migrations/2021_04_04_143826_add_delete_cascade_to_vote_id_column_on_member_vote_table.php

Co-authored-by: Till Prochaska <mail@tillprochaska.de>

Generate Sharepic for scraped final votes

---

.github/workflows/ci.yml
app/app/Mixins/CollectionMixin.php
app/app/Mixins/ComponentAttributeBagMixin.php
app/app/Providers/AppServiceProvider.php
app/database/factories/VoteFactory.php
app/tests/Feature/Http/Votes/SharePicturesTest.php
app/tests/Pest.php
app/tests/Unit/Macros/CollectionMixinTest.php
app/tests/Unit/Macros/ComponentAttributeBagMixinTest.php
docker-compose.yml
scrapers/ep_votes/api.py
scrapers/ep_votes/scrapers.py
scrapers/tests/test_api.py
scrapers/tests/test_helpers.py

Increase test coverage

---

scrapers/ep_votes/scrapers.py

Sends a fake user agent (+ some additional headers a real browser would usually send)

Disguise user agent

---

app/app/Http/Controllers/VotingListsController.php
app/composer.json
app/composer.lock
app/routes/web.php
app/tests/Feature/Http/VotingLists/CsvTest.php
app/tests/Pest.php

Add CSV for Download with votingList on /votes/{id}.csv

---

.editorconfig
app/package-lock.json
app/package.json
app/resources/css/app.css
app/resources/css/components/action-panel.css
app/resources/css/components/button.css
app/resources/css/components/input.css
app/resources/css/components/list.css
app/resources/css/components/stack.css
app/resources/css/components/tabs.css
app/resources/css/components/vote-result-chart.css
app/resources/css/global/typography.css
app/resources/css/variables.css
app/resources/js/app.js
app/resources/js/components/list-item.js
app/resources/lang/en/components.php
app/resources/lang/en/voting-lists.php
app/resources/views/components/action-panel.blade.php
app/resources/views/components/app.blade.php
app/resources/views/components/button.blade.php
app/resources/views/components/country-list-item.blade.php
app/resources/views/components/group-list-item.blade.php
app/resources/views/components/input.blade.php
app/resources/views/components/list-item.blade.php
app/resources/views/components/list.blade.php
app/resources/views/components/member-list-item.blade.php
app/resources/views/voting-lists/show.blade.php
app/tests/Unit/Components/ButtonTest.php

Co-authored-by: Till Prochaska <mail@tillprochaska.de>

Limit initial length of MEP and country lists

---

app/app/Http/Controllers/VotingListsController.php
app/app/Vote.php
app/resources/css/app.css
app/resources/css/components/action-panel.css
app/resources/css/components/callout.css
app/resources/css/components/input.css
app/resources/css/components/vote-card.css
app/resources/css/global/base.css
app/resources/css/global/typography.css
app/resources/css/variables.css
app/resources/lang/en/votes.php
app/resources/lang/en/voting-lists.php
app/resources/views/components/action-panel.blade.php
app/resources/views/components/callout.blade.php
app/resources/views/components/vote-card.blade.php
app/resources/views/voting-lists/related.blade.php
app/resources/views/voting-lists/show.blade.php
app/routes/web.php
app/tests/Feature/Http/VotingLists/RelatedTest.php
app/tests/Feature/Http/VotingLists/ShowTest.php
app/tests/Unit/VoteTest.php

Indicator for (non) final votes

---

app/app/Actions/CompileStatsAction.php

Remove now unnecessary typecasts since the tests run in MariaDB

---

docker-compose.yml

@linusha Hatte noch eine Anpassung der Docker-Config vergessen, um mein Debugging-Tool zu nutzen…

Add docker config to support Ray logging

---

app/app/Actions/GenerateVoteSharePicAction.php
app/app/Actions/MatchVotesAndVotingListsAction.php
app/app/Member.php
app/app/VotingList.php
app/resources/css/app.css
app/resources/css/components/button.css
app/resources/css/components/share-button.css
app/resources/css/global/base.css
app/resources/lang/en/voting-lists.php
app/resources/views/components/app.blade.php
app/resources/views/components/button.blade.php
app/resources/views/components/share-button.blade.php
app/resources/views/monitoring/index.blade.php
app/resources/views/voting-lists/index.blade.php
app/resources/views/voting-lists/related.blade.php
app/resources/views/voting-lists/show.blade.php
app/resources/views/voting-lists/summary.blade.php
app/routes/console.php
app/tests/Feature/Http/VotingLists/ShowTest.php
app/tests/Unit/Actions/GenerateVoteSharePicActionTest.php
app/tests/Unit/Actions/MatchVotesAndVotingListsActionTest.php
app/tests/Unit/VotingListTest.php

Fix SharePicAction to use VotingLists instead of Votes

---

app/app/VotingList.php
app/resources/views/voting-lists/show.blade.php
app/tests/Unit/VotingListTest.php

@linusha Didn’t notice this during review, but this should use Eloquent’s attribute accessors…

Use attribute accessor for share picture url

---

app/app/Http/Controllers/VotingListsController.php
app/routes/web.php
app/tests/Feature/Http/VotingLists/ShowTest.php
app/tests/Pest.php

Let shortUrls for VotingLists redirect to /votes/:id

---

app/app/Vote.php
app/app/VotingList.php
app/resources/views/voting-lists/show.blade.php
app/tests/Feature/Http/VotingLists/ShowTest.php
app/tests/Unit/VoteTest.php

Do not show URL in callout for non-matched primary votes

---

app/database/seeds/GroupSeeder.php
scrapers/ep_votes/models.py

Add name variant for left group

---

scrapers/ep_votes/scrapers.py
scrapers/tests/data/ficheprocedure_a9-0115-2021.html
scrapers/tests/test_scrapers.py

Fix type error if summary button does not exist

---

scrapers/ep_votes/scrapers.py

Add new group group positions for 8th parliamentary term

---

app/resources/css/components/share-picture.css
app/resources/views/voting-lists/share-picture.blade.php

Fix share picture styles

---

app/app/Actions/ScrapeSummaryAction.php
app/tests/Unit/Actions/ScrapeSummaryActionTest.php
app/tests/Unit/Actions/ScrapeVoteCollectionsActionTest.php
scrapers/ep_votes/api.py
scrapers/ep_votes/scrapers.py
scrapers/tests/data/ficheprocedure_a9-0149-2021.html
scrapers/tests/test_scrapers.py

Otherwise we’d get incorrect summary IDs in case there are multiple votes with summaries for a legislative procedure.
Close #401

Scrape summary ID based on date/week of vote

---

scrapers/ep_votes/scrapers.py

Some sources do not return the correct character encoding in the HTTP headers which confuses request when trying to decode the response. In those cases, we need to force the correct encoding.
Fixes EP-VOTES-2A, closes #414

Enforce response character encoding

---

ansible/roles/meilisearch/tasks/installation.yml
ansible/roles/meilisearch/templates/etc/services.d/meilisearch.ini.j2
ansible/roles/setup/tasks/main.yml
ansible/vars/general.yml
ansible/vars/search.yml

Beispiel
```
curl "https://search.howtheyvote.eu/indexes/voting_lists/search?q=covid-19" -H 'X-Meili-API-Key: PUBLIC KEY'
```

Expose Meilisearch on subdomain

---

app/resources/lang/en/voting-lists.php

Use non breaking space to prevent line breaks

---

app/resources/css/components/action-panel.css

| Before | After |
| - | - |
| <img width="720" alt="Screen Shot 2021-08-18 at 13 22 19" src="https://user-images.githubusercontent.com/1512805/129889815-72173ec6-c4f6-4578-9739-5c8dd3fe628d.png"> | <img width="711" alt="Screen Shot 2021-08-18 at 13 23 11" src="https://user-images.githubusercontent.com/1512805/129889775-7844e7e0-4a59-4cfb-8fc9-f14ef1049d85.png"> |

Fix action panel gap

---

scrapers/ep_votes/scrapers.py
scrapers/tests/test_scrapers.py

Handle alternative names of MEPs

---

app/app/Enums/VoteResultEnum.php
app/app/VotingList.php
app/resources/css/components/share-picture.css
app/resources/lang/en/voting-lists.php
app/resources/views/voting-lists/share-picture.blade.php
app/resources/views/voting-lists/show.blade.php
app/tests/Feature/Http/VotingLists/SharePicturesTest.php
app/tests/Unit/VotingListTest.php

Show result of Vote in share-picture

---

app/package-lock.json
app/package.json
app/resources/js/app.js
app/resources/views/components/app.blade.php
app/resources/views/components/search.blade.php

Prefetch preconnect

---

app/resources/css/components/footer.css

Add horizontal padding to footer

---

app/app/Http/Controllers/MembersController.php
app/tests/Feature/Http/Members/ShowTest.php

Show votes in reverse chronological order on members page

---

app/resources/css/app.css
app/resources/css/components/loading-spinner.css
app/resources/css/global/typography.css
app/resources/js/components/search-results-page.js
app/resources/views/components/loading-spinner.blade.php
app/resources/views/components/search-results-page.blade.php

https://user-images.githubusercontent.com/1512805/131401980-8e235126-6fcf-4229-92fa-f02ce3fa6c59.mov
Fix #491

Do not display "no results" when initial results haven't yet been loaded

---

app/resources/views/components/app.blade.php

Falsches Blau… (Aber habe heute gelernt, dass man darin auch Custom Properties verwenden kann.)

Fix theme color

---

app/resources/css/app.css
app/resources/css/components/error-page.css
app/resources/js/app.js
app/resources/js/components/eye.js
app/resources/lang/en/errors.php
app/resources/views/components/error-page.blade.php
app/resources/views/components/eyes.blade.php
app/resources/views/errors/404.blade.php
app/resources/views/errors/500.blade.php
app/resources/views/errors/503.blade.php

https://user-images.githubusercontent.com/1512805/131740264-5d4b0aac-65c0-4b5d-989f-72c5fb32259b.mov
Close #484

Add custom 404, 500, 503 error pages

---

README.md

Fix typo in readme code

---

app/app/Mixins/AbstractRenderedMixin.php
app/package-lock.json
app/package.json
app/resources/css/app.css
app/resources/css/components/button.css
app/resources/css/components/list.css
app/resources/css/components/position-select.css
app/resources/css/components/thumb.css
app/resources/css/variables.css
app/resources/js/app.js
app/resources/js/components/list-item.js
app/resources/lang/en/components.php
app/resources/lang/en/enums.php
app/resources/views/components/button.blade.php
app/resources/views/components/list-item.blade.php
app/resources/views/components/list.blade.php
app/resources/views/components/member-list-item.blade.php
app/resources/views/components/position-select.blade.php
app/resources/views/components/voting-list/members-list.blade.php
app/tests/Unit/Components/PositionSelectTest.php

https://user-images.githubusercontent.com/1512805/186463307-c756f012-b370-4482-b37e-d2f9d0c8b33f.mov
(MEP photos aren’t displayed because I don’t have a copy of them in my dev environment.)
To do:

Filter members by vote

---

app/app/Member.php
app/routes/console.php
app/tests/Unit/MemberTest.php

The missing pictures in production are already fixed :)

Scrape pictures for members without picture in scrape:all

---

app/routes/console.php

Only scrape concluded `Sessions` automatically

---

README.md
frontend/src/pages/AboutPage.tsx

The 10ths EP is made up of 720 MEPs, even though right now there are only 719 active MEPs: https://www.politico.eu/newsletter/brussels-playbook/von-der-leyens-secrets-haunt-vote/

Update total number of MEPs

---

README.md

Add linux permissions fix for docker to README

---

backend/howtheyvote/analysis/votes.py

Found it here: https://howtheyvote.eu/votes/171706

Add additional main vote description

---

backend/howtheyvote/analysis/helpers.py
backend/tests/analysis/test_helpers.py

As found here: https://www.europarl.europa.eu/news/en/press-room/20250331IPR27557/sustainability-and-due-diligence-meps-agree-to-delay-application-of-new-rules

Add alternative phrasing for press-release voting count detection

---

backend/howtheyvote/api/votes_api.py

Add VOT lists to data sources

---

backend/tests/api/test_votes_api.py

Wrote these to facilitate debugging something locally as this was previously untested.

Add additional votes API tests

---

backend/howtheyvote/cli/temp.py

This is required after implementing 492d0be.

Add CLI command to re-scrape all referenced documents
